version: "3"

services:

  cassandra:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/db/Dockerfile
    image: cassandra
    container_name: cassandra
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "/usr/local/bin/docker-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

  book_app:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
    image: bookapp
    ports:
      - "3000:3000" 
    container_name: book_app
    networks:
      - cassandra-net
    depends_on:
      - cassandra
    command: bash -c "sleep 120 && node app.js"

networks:
  cassandra-net: